### ISSUE TITLE
A checklist for tweaking the website

### ISSUE THREAD

**Issue by wehs7661** [wehs7661/weitse-hsu#1]
Below is a checklist for things to be improved (if possible) for the website
- [x]  Adjust the font size of the fonts in the About section. 
- [x] Change the color of "About Me".
- [x] Change the color of the filter button in the section of Research Projects.
- [x] Enlarge the font size in the cards in Research Experience.
- [x] Change the color of the side bar in Research Experience.
- [x] Increase and unify the sizes of the school logos in the section of Research Experience. 
- [x] Enlarge the padding between different blocks in Research Projects.
- [x] Add the publication search engine.
- [x] Change the color of "Interests" and "Education" in the About section.
- [x] Add Google analytics (Check [this](https://www.youtube.com/watch?v=njri8_gJTs0))
- [x] Add slides to publication pages as needed. (Check [this](https://wowchemy.com/docs/content/slides/))
- [x] Set up the domain for the website (Check [this](https://georgecushen.com/create-your-website-with-hugo/))

**Comment by wehs7661** [comment]
The first 5 action items in the checklist can be accomplished by modifying `custom.scss`, which can be added to `assets/scss` (create the folder if it isn't there) to override the default settings looked up and adopted in [wowchemy](https://github.com/wowchemy/wowchemy-hugo-themes/tree/main/wowchemy/assets/scss/wowchemy). Below are the code blocks in `custom.scss` relevant for making the changes for the first 5 action items in the checklist.

- Adjust the font size of the fonts in the About section
   ```scss=1
   body {
     font-family: inherit;
     font-size: 1rem;   // for the about section
     ...
   }
   ```
- Change the color of "About Me".
  ```
  .dark h1,
  .dark h2,
  .dark h3,
  .dark h4,
  .dark h5,
  .dark h6 {
    color: #EAF38B;  // e.g. About Me
  }
  ``` 
- Change the color of the filter button in the section of Research Projects.
  ```
  .btn-primary {
    border-color: #6ec6ff !important;
    background: #6ec6ff !important;
  }

  .btn-toolbar .btn.btn-primary:hover,
  .btn-toolbar .btn.btn-primary:focus {
    background-color: #82deeb !important;
  }

  .btn-toolbar .btn.btn-primary:active,
  .btn-toolbar .btn.btn-primary.active {
    background-color: #0095eb !important;
  }
  ```
- Enlarge the font size in the cards in Research Experience.
  ```
  .dark .experience .card-text,
  .dark .experience .card-text p {
    color:rgb(248, 248, 242) !important;
    font-size: 0.8rem !important;
  }
  ```
- Change the color of the side bar in Research Experience.
  ```
  .dark .experience .m-2 .border,
  .experience .col.border-right {
    border-color: #6ec6ff !important;
  }

  .experience .m-2 .border.exp-fill {
    background-color: #6ec6ff !important;
  }
  ```

**Comment by wehs7661** [comment]
For the record, I added the following code to `custom.scss` to add a scroll bar to large code blocks and make it always visible:
```
/* Make the code block scrollable in the vertical direction */
pre {
  line-height: 1.5em; /* this is the default for code blocks*/
  /* Below we set the maximum height as 20 lines + 0.5em (bottom margin) + 0.5 em (scrollbar heigh) */
  max-height: calc(20 * 1.5em + 0.5em + 0.5em); /* The maximum is 10 lines here. 0.5em is the bottom margin. */
  overflow-y: auto; /* Add a vertical scroll bar when the code block exceeds the maximum height */
}

pre::-webkit-scrollbar {
  /* Note that in our settings, 1em=14px */
  -webkit-appearance: none;
  width: 0.5em;
  height: 0.5em;
}

pre::-webkit-scrollbar-thumb {
  border-radius: 0.5em;
  background-color: rgba(255, 255, 255, .54);
}

/* To get rid of the little square at the bottom right corner of the code block */
pre::-webkit-scrollbar-corner {
  background-color: transparent;
}
```
The change was made in commit 457d398825a424af8fd5c15c742e70a79396c747.
